Repository open-education-hub/open-education-hub-site, pull requests merged in 2023-09, with the labels that each got.

#48 events: Update location for M4 event
  website/docs/events/m4.md
Labels: enhancement

#49 events: Add skeleton slides for M4 event (conference)
  website/docs/events/m4-slides/.gitignore
  website/docs/events/m4-slides/.slides/conclusion.md
  website/docs/events/m4-slides/.slides/infrastructure.md
  website/docs/events/m4-slides/.slides/methodology.md
  website/docs/events/m4-slides/.slides/overview.md
  website/docs/events/m4-slides/.slides/repositories.md
  website/docs/events/m4-slides/Makefile
  website/docs/events/m4-slides/media/.gitignore
  website/docs/events/m4-slides/slides.mdpp
Labels: enhancement

#50 workflows: Use GitHub actions from OpenEdu repo
  .github/workflows/actions.yml
  .github/workflows/super-linter.yml
Labels: bug

#52 events/m4: Add slide about OS repo
  website/docs/events/m4-slides/.slides/repositories.md
Labels: documentation, enhancement

#58 m4-slides: Add conclusion section
  website/docs/events/m4-slides/.slides/conclusion.md
Labels: enhancement
