Repository open-education-hub/open-education-hub-site, pull requests merged in 2023-03, with the labels that each got.

#33 events/m3: Add description and skeleton for summary
  website/docs/events/m3.md
Labels: documentation

#34 Update logo
  website/docusaurus.config.js
Labels: enhancement

#36 website: Add slogan and disclaimer required by EEA
  website/docusaurus.config.js
  website/src/pages/index.js
Labels: enhancement

#38 events/m3: Fix Discord link
  website/docs/events/m3.md
Labels: bug

#41 events/m3: Add content for evaluation and next-steps sections
  website/docs/events/m3-slides/.slides/evaluation.md
  website/docs/events/m3-slides/.slides/next-steps.md
  website/docs/events/m3-slides/media/avg-grade.png
  website/docs/events/m3-slides/media/feedback-assistant-lab.png
  website/docs/events/m3-slides/media/feedback-assistant-lecture.png
  website/docs/events/m3-slides/media/feedback-students-lab.png
  website/docs/events/m3-slides/media/feedback-students-lecture.png
  website/docs/events/m3-slides/media/feedback-students-other.png
Labels: documentation, enhancement
